# Spring & LDAP Configuration
spring:
  application:
    name: @project.name@
  main:
    allow-bean-definition-overriding: true
  ldap:
    embedded:
      ldif: ldap.ldif
      base-dn: dc=richard,dc=com
      port: 8389

# Swagger Documentation
swagger:
  service:
    version: "1.0.0"
    title: ${spring.application.name}
    description: "Skeleton app swagger"
